### ISSUE TITLE
Question about Fourier Transform spectrum shifting

### ISSUE THREAD

**Issue by minh-nguyenhoang** [1911cty/Unbiased-Fast-Fourier-Convolution#4]
Should the function in [line 84](https://github.com/1911cty/Unbiased-Fast-Fourier-Convolution/blob/db0ec7ebf68a9643bc7f13e837489d554cba067c/uffc.py#L84) be `torch.fft.ifftshift`, as it should be the inverse of the previous `torch.fft.fftshift` operator?

**Comment by 1911cty** [comment]
Thank you for pointing out this issue!  When the input size is odd, repeatedly using fftshift does indeed cause problems.
